- name: Copy console fonts
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/usr/share/kbd/consolefonts/{{ item }}"
    dest: /usr/share/kbd/consolefonts/
    owner: root
    group: root
    mode: "0644"
  loop:
    - spleen-5x8.psfu
    - spleen-6x12.psfu
    - spleen-8x16.psfu
    - spleen-12x24.psfu
    - spleen-16x32.psfu
    - spleen-32x64.psfu
- name: Copy console configuration
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/vconsole.conf"
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: "0644"
- name: Update font cache
  ansible.builtin.command: fc-cache -fv
