- name: Force remove packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg: "{{ remove }}"
    state: absent
    update_cache: true
- name: Install packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg: "{{ install }}"
