---
- hosts: melee
  remote_user: gianfranco
  gather_facts: no
  tasks:

  - import_tasks: tasks/system.yml
    vars:
      username: gianfranco
      pkgs:
        - firefox
        - xfce4
        - xfce4-goodies

  - import_tasks: tasks/autologin.yml
    vars:
      username: gianfranco

  - import_tasks: tasks/bluetooth.yml

  - import_tasks: tasks/xfce.yml

  - import_tasks: tasks/retrogaming.yml
    vars:
      username: gianfranco

  - name: Copy dotfiles
    ansible.builtin.copy:
      src: "dotfiles/{{dotfiles}}/{{item.s}}"
      dest: "/home/gianfranco/{{item.d}}"
      owner: gianfranco
      group: gianfranco
      mode: "{{item.m}}"
    loop:
      - {s: ".bashrc", d: "", m: "0644"}
      - {s: ".bash_profile", d: "", m: "0644"}
      - {s: ".xinitrc", d: "", m: "0744"}
      - {s: "wallpaper.jpg", d: "", m: "0644"}
