---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:

  - import_tasks: tasks/system.yml
    vars:
      username: carloratm
      pkgs:
        - keepassxc
        - libgepub
        - libgsf
        - poppler-glib
        - qutebrowser
        - xbindkeys

  - import_tasks: tasks/git.yml

  - import_tasks: tasks/xmonad.yml

  - import_tasks: tasks/amiga.yml

  - name: Stow dotfiles
    ansible.builtin.shell: stow "{{dotfiles}}" --target="/home/carloratm"
    args:
      chdir: dotfiles
