---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    systemname: personal_system
    username: carloratm
    pkgs:
      - xorg
      - xorg-xinit
      - xorg-fonts-encodings
      - starship
      - fd
      - eza
      - bat
      - ripgrep
      - gdu
      - fzf
      - autorandr
      - awesome
      - xfce4-appfinder
      - xfce4-power-manager
      - elementary-icon-theme
      - keepassxc
      - thunar
      - tumbler
      - gvfs
      - gthumb
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - ffmpegthumbnailer
      - poppler-glib
      - libgsf
      - libgepub
      - libopenraw
    services:
      - sshd
  tasks:
    - ansible.builtin.include_tasks: tasks/system.yml
    - ansible.builtin.include_tasks: tasks/pacman.yml
    - ansible.builtin.include_tasks: tasks/services.yml
    - ansible.builtin.include_tasks: tasks/dotfiles.yml
    - ansible.builtin.include_tasks: tasks/fc_cache.yml
    - ansible.builtin.include_tasks: tasks/xfce.yml
