---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:

  - import_tasks: tasks/system.yml
    vars:
      username: carloratm
      pkgs:
        - keepassxc
        - qutebrowser

  - import_tasks: tasks/git.yml

  - import_tasks: tasks/awesomewm.yml

  - name: Stow dotfiles
    ansible.builtin.shell: stow "{{ host }}" --target="{{lookup('env', 'HOME')}}"
    args:
      chdir: dotfiles
