---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    host: scumm
    user:
      username: carloratm
      groups:
        - carloratm
    pkgs:
      - base
      - base-devel
      - xorg
      - xorg-xinit
      - git
      - vim
      - terminus-font
      - bash-completion
      - starship
      - fd
      - ripgrep
      - stow
      - inotify-tools
      - libiconv
      - upower
      - ansible
      - fzf
      - xfce4
      - xfce4-goodies
      - alacritty
      - firefox
      - keepassxc
      - nix
    services:
      - nix-daemon
  tasks:
    - ansible.builtin.include_tasks: tasks/user.yml
    - ansible.builtin.include_tasks: tasks/locale.yml
    - ansible.builtin.include_tasks: tasks/vconsole.yml
    - ansible.builtin.include_tasks: tasks/pacman.yml
    - ansible.builtin.include_tasks: tasks/nix.yml
    - ansible.builtin.include_tasks: tasks/services.yml
    - ansible.builtin.include_tasks: tasks/dotfiles.yml
    - ansible.builtin.include_tasks: tasks/xfce.yml
    - ansible.builtin.include_tasks: tasks/xfce-panel.yml
  handlers:
    - ansible.builtin.include_tasks: tasks/locale_gen.yml
