---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
# SYSTEM PACKAGES {{{
  - name: Force remove packages
    become: yes
    become_method: ansible.builtin.su
    community.general.pacman:
      pkg:
      - lftp
      state: absent
      update_cache: true
  - name: Install packages
    become: yes
    become_method: ansible.builtin.su
    community.general.pacman:
      pkg:
      - alacritty
      - ansible
      - awesome
      - base
      - base-devel
      - bash-completion
      - bat
      - curl
      - elementary-icon-theme
      - eza
      - fd
      - fontconfig
      - fzf
      - gdu
      - git
      - inotify-tools
      - keepassxc
      - libnotify
      - mupdf
      - networkmanager
      - noto-fonts
      - noto-fonts-emoji
      - openssh
      - pavucontrol
      - pulseaudio
      - qutebrowser
      - ripgrep
      - starship
      - stow
      - sudo
      - unzip
      - vim
      - wget
      - xfce4-appfinder
      - xfce4-power-manager
      - xfce4-screenshooter
      - xfce4-settings
      - xorg
      - xorg-xinit
      update_cache: true
# }}}

# USER AND GROUPS {{{
  - name: Create base groups
    become: yes
    become_method: ansible.builtin.su
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    loop:
      - users
      - "{{ username }}"
  - name: Create user
    become: yes
    become_method: ansible.builtin.su
    ansible.builtin.user:
      name: "{{ username }}"
      shell: /bin/bash
      groups:
        - users
        - disk
        - adm
        - audio
        - video
        - disk
        - sys
        - tty
        - daemon
        - input
  - name: Add user to sudoers
    become: yes
    become_method: ansible.builtin.su
    community.general.sudoers:
      name: sudo
      state: present
      user: "{{ username }}"
      commands: ALL
# }}}

# SYSTEM CONFIG {{{
  - name: Set hostname
    become: yes
    ansible.builtin.hostname:
      name: "{{ host }}"
  - name: Copy motd
    become: yes
    ansible.builtin.copy:
      src: "templates/{{ host }}/etc/motd"
      dest: /etc/motd
      owner: root
      group: root
      mode: "0644"
  - name: Set timezone
    become: yes
    community.general.timezone:
      name: Europe/Vienna
  - name: Copy locale conf
    become: yes
    ansible.builtin.copy:
      src: "templates/{{ host }}/etc/locale.conf"
      dest: /etc/locale.conf
      owner: root
      group: root
      mode: "0644"
  - name: Copy timezone
    become: yes
    ansible.builtin.copy:
      src: "templates/{{ host }}/etc/timezone"
      dest: /etc/timezone
      owner: root
      group: root
      mode: "0644"
  - name: Generate locales
    become: yes
    community.general.locale_gen:
      name: "{{ item }}"
      state: present
    loop:
      - en_US.UTF-8
      - it_IT.UTF-8
      - de_DE.UTF-8
# }}}

# GIT CONFIG {{{
  - name: Config global git
    community.general.git_config:
      name: "{{ item.name }}"
      scope: global
      value: "{{ item.value }}"
    loop:
      - {name: user.name, value: "Ascani Carlo"}
      - {name: alias.co, value: checkout}
      - {name: alias.s, value: status}
      - {name: init.defaultBranch, value: main}
  - name: Set git email
    community.general.git_config:
      name: user.email
      scope: global
      value: "{{ email }}"
# }}}

# DOTFILES {{{
  - name: Stow dotfiles
    ansible.builtin.shell: stow "{{ host }}" --target="{{lookup('env', 'HOME')}}"
    args:
      chdir: dotfiles
# }}}

# SERVICES {{{
  - name: Start and enable serives
    become: yes
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - NetworkManager
      - sshd
# }}}

# FONTS {{{
  - name: Copy console fonts
    become: yes
    ansible.builtin.copy:
      src: "templates/{{ host }}/usr/share/kbd/consolefonts/{{ item }}"
      dest: /usr/share/kbd/consolefonts/
      owner: root
      group: root
      mode: "0644"
    loop:
      - spleen-5x8.psfu
      - spleen-6x12.psfu
      - spleen-8x16.psfu
      - spleen-12x24.psfu
      - spleen-16x32.psfu
      - spleen-32x64.psfu
  - name: Copy console configuration
    become: yes
    ansible.builtin.copy:
      src: "templates/{{ host }}/etc/vconsole.conf"
      dest: /etc/vconsole.conf
      owner: root
      group: root
      mode: "0644"
  - name: Update font cache
    ansible.builtin.command: fc-cache -fv
# }}}

# XFCE {{{
  - name: Configure power manager
    community.general.xfconf:
      channel: xfce4-power-manager
      property: "/xfce4-power-manager{{item.p}}"
      value_type: "{{item.t}}"
      value: "{{item.v}}"
    loop:
      - {p: /battery-button-action, t: int, v: 0}
      - {p: /blank-on-ac, t: int, v: 0}
      - {p: /blank-on-battery, t: int, v: 0}
      - {p: /brightness-level-on-acc, t: int, v: 100}
      - {p: /brightness-level-on-battery, t: int, v: 100}
      - {p: /brightness-on-ac, t: int, v: 9}
      - {p: /brightness-on-battery, t: int, v: 9}
      - {p: /brightness-switch, t: int, v: 0}
      - {p: /brightness-switch-restore-on-exit, t: int, v: 1}
      - {p: /critical-power-action, t: int, v: 3}
      - {p: /critical-power-level, t: int, v: 5}
      - {p: /dpms-enabled, t: bool, v: false}
      - {p: /dpms-on-battery-off, t: int, v: 19}
      - {p: /dpms-on-battery-sleep, t: int, v: 18}
      - {p: /general-notification, t: bool, v: true}
      - {p: /handle-brightness-keys, t: bool, v: false}
      - {p: /hibernate-button-action, t: int, v: 0}
      - {p: /inactivity-on-ac, t: int, v: 14}
      - {p: /inactivity-on-battery, t: int, v: 14}
      - {p: /lid-action-on-ac, t: int, v: 0}
      - {p: /lid-action-on-battery, t: int, v: 0}
      - {p: /lock-screen-suspend-hibernate, t: bool, v: false}
      - {p: /power-button-action, t: int, v: 4}
      - {p: /show-panel-label, t: int, v: 0}
      - {p: /show-presentation-indicator, t: bool, v: false}
      - {p: /show-tray-icon, t: bool, v: false}
      - {p: /sleep-button-action, t: int, v: 0}
# }}}
