---
- hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: no
  connection: local
  vars:
    pkgs:
      - ratm-base
      - ratm-desktop
      - libdockapp
      - wmbattery
      - wmtime
      - paginator-git
      - firefox
      - keepassxc
      - slock
  tasks:
    - ansible.builtin.include_tasks: tasks/locale.yml
    - ansible.builtin.include_tasks: tasks/vconsole.yml
    - ansible.builtin.include_tasks: tasks/pacman.yml
  handlers:
    - ansible.builtin.include_tasks: tasks/locale_gen.yml

- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: STOW DOTFILES
      ansible.builtin.command: stow home --target={{ lookup('env', 'HOME') }}
