---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    host: scumm
    user:
      username: carloratm
      groups: [carloratm]
    pkgs:
      - xorg
      - xorg-xinit
      - xorg-fonts-encodings
      - starship
      - fd
      - ripgrep
      - fzf
      - autorandr
      - awesome
      - xfce4-appfinder
      - xfce4-power-manager
      - elementary-icon-theme
      - keepassxc
      - nix
      - direnv
    services:
      - sshd
      - nix-daemon
  tasks:
    - ansible.builtin.include_tasks: tasks/system.yml
    - ansible.builtin.include_tasks: tasks/pacman.yml
    - ansible.builtin.include_tasks: tasks/services.yml
    - ansible.builtin.include_tasks: tasks/dotfiles.yml
    - ansible.builtin.include_tasks: tasks/fc_cache.yml
