---
- name: System configuration
  hosts: all
  gather_facts: false
  become: true
  tasks:

# Load vars {{{
    - name: Load vars
      ansible.builtin.include_vars:
        file: "./vars/{{ profile }}.yml"
# }}}
# Install packages {{{
    - name: Force uninstall packages
      ansible.builtin.apt:
        state: absent
        purge: true
        pkg:
          - cups
          - cups-browsed
          - cups-client
          - cups-common
          - cups-core-drivers
          - cups-daemon
          - cups-filters
          - cups-filters-core-drivers
          - cups-ipp-utils
          - cups-pk-helper
          - cups-ppdc
          - cups-server-common
    - name: Common packages # noqa package-latest
      ansible.builtin.apt:
        update_cache: true
        state: latest
        pkg:
          - network-manager
          - adwaita-icon-theme
          - build-essential
          - bash-completion
          - curl
          - fd-find
          - fonts-spleen
          - fonts-noto
          - fonts-noto-color-emoji
          - pavucontrol
          - pulseaudio
          - ripgrep
          - tree
          - vim
          - wget
          - xdg-user-dirs
          - xorg
    - name: User packages # noqa package-latest
      ansible.builtin.apt:
        state: latest
        pkg: "{{ sys.packages | default([]) }}"
# }}}
# Hostname {{{
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ sys.hostname }}"
# }}}
# Locales {{{
    - name: Ensure a locale exists
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop:
        - en_US.UTF-8
        - it_IT.UTF-8
        - de_DE.UTF-8
# }}}
# User and groups {{{
    - name: Create base groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - users
        - "{{ sys.user.username }}"
        - sudo
        - wheel
    - name: "Create user {{ sys.user.name }}"
      ansible.builtin.user:
        name: "{{ sys.user.username }}"
        shell: /bin/bash
        groups:
          - audio
          - bluetooth
          - cdrom
          - floppy
          - input
          - kvm
          - sudo
          - tty
          - users
          - video
          - wheel
    - name: Put user in sudoers
      ansible.builtin.copy:
        src: "templates/sudoer.j2"
        dest: "/etc/sudoers.d/{{ sys.user.username }}"
        owner: root
        group: root
        mode: "0440"
# }}}
# Vim {{{
    - name: Configure vim
      ansible.builtin.copy:
        src: ./templates/vimrc.local
        dest: /etc/vim/vimrc.local
        owner: root
        group: root
        mode: "0666"
# }}}
# Git {{{
    - name: Configure git
      community.general.git_config:
        name: "{{ item.n }}"
        scope: system
        value: "{{ item.v }}"
      loop:
        - {n: core.editor, v: vim}
        - {n: user.name, v: sys.user.name}
        - {n: user.username, v: sys.user.username}
        - {n: user.email, v: sys.user.email}
        - {n: alias.s, v: status}
        - {n: alias.co, v: checkout}
# }}}
# Services {{{
    - name: System services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - sshd
# }}}
# Dotfiles {{{
    - name: Make sure destination dir exists
      become: true
      become_user: "{{ sys.user.username }}"
      ansible.builtin.file:
        path: "/home/{{ sys.user.username }}/{{ item | dirname }}"
        state: directory
        mode: "0755"
        owner: "{{ sys.user.username }}"
        group: "{{ sys.user.username }}"
      loop: "{{ sys.dots | default([]) }}"
    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "dots/{{ profile }}/{{ item }}"
        dest: "/home/{{ sys.user.username }}/{{ item }}"
        owner: "{{ sys.user.username }}"
        group: "{{ sys.user.username }}"
        mode: preserve
      loop: "{{ sys.dots | default([]) }}"
    - name: Make user dirs
      become: true
      ansible.builtin.file:
        path: "/home/{{ sys.user.username }}/{{ item }}"
        state: directory
        mode: "0711"
        owner: "{{ sys.user.username }}"
        group: "{{ sys.user.username }}"
      loop:
        "{{ sys.user.dirs | default([]) }}"
    - name: Udpate xdg user dirs # noqa no-changed-when
      become: true
      become_user: "{{ sys.user.username }}"
      ansible.builtin.command:
        cmd: xdg-user-dirs-update
        chdir: "/home/{{ sys.user.username }}"
# }}}
# Starship {{{
    - name: Maybe install starship
      become: true
      when: sys.starship | default(false) | bool()
      block:
        - name: Check if starship exists
          ansible.builtin.stat:
            path: /usr/local/bin/starship
          register: starship_bin
        - name: Dowload the starship install script
          ansible.builtin.get_url:
            url: https://starship.rs/install.sh
            dest: /tmp/starship_installer
            mode: "0777"
          register: starship_installer
          when: not starship_bin.stat.exists
        - name: Install starship
          ansible.builtin.command:
            cmd: /tmp/starship_installer --yes
            creates: /usr/local/bin/starship
          when: not starship_bin.stat.exists
        - name: Remove installer
          ansible.builtin.file:
            path: "{{ starship_installer.dest }}"
            state: absent
          when: not starship_bin.stat.exists
# }}}
# Devbox {{{
    - name: Maybe install devbox
      become: true
      when: sys.devbox | default(false) | bool()
      block:
        - name: Check if devbox exists
          ansible.builtin.stat:
            path: /usr/local/bin/devbox
          register: devbox_bin
        - name: Download devbox
          ansible.builtin.get_url:
            url: https://get.jetify.com/devbox
            dest: /tmp/devbox_installer
            mode: "0777"
          register: devbox_installer
          when: not devbox_bin.stat.exists
        - name: Install devbox
          become: true
          ansible.builtin.command:
            cmd: /tmp/devbox_installer --force
            creates: /usr/local/bin/devbox
          when: not devbox_bin.stat.exists
        - name: Remove installer
          ansible.builtin.file:
            path: "{{ devbox_installer.dest }}"
            state: absent
          when: not devbox_bin.stat.exists
        - name: Fix devbox bin permissions
          ansible.builtin.file:
            path: /usr/local/bin/devbox
            mode: "0777"
# }}}
# Network {{{
#   - name: Configure home wifi connection
#     community.general.nmcli:
#       type: wifi
#       conn_name: Casa
#       ifname: "{{ sys.net.interface }}"
#       ssid: AscaniFerretti
#       ip4: "{{ sys.net.ip }}"
#       gw4: "192.168.1.1"
#       method6: "disabled"
#       wifi_sec:
#         key-mgmt: wpa-psk
#         psk: "g:B4$1F\\A\\@X."
#       autoconnect: yes
#       state: present
#   - name: Restart NetworkManager
#     ansible.builtin.systemd:
#       name: NetworkManager
#       state: restarted
#       enabled: true
# }}}
