TERM = "xterm-256color"
import = ["/home/carloratm/.config/alacritty/dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 22

[font.bold]
family = "Spleen"
style = "Regular"

[font.bold_italic]
family = "Spleen"
style = "Regular"

[font.italic]
family = "Spleen"
style = "Regular"

[font.normal]
family = "Spleen"
style = "Regular"

[mouse]
hide_when_typing = true

[window.dimensions]
columns = 80
lines = 24
