[colors]
author = "Carlo Ascani (https://tilde.club/~carloratm)"
description = "My personal dark Theme"
name = "Dark Theme"

[colors.bright]
black = "#686868"
blue = "#5454ff"
cyan = "#54ffff"
green = "#54ff54"
magenta = "#ff54ff"
red = "#ff5454"
white = "#ffffff"
yellow = "#ffff54"

[colors.cursor]
cursor = "#ff0000"
text = "#ffffff"

[colors.normal]
black = "#202020"
blue = "#1818b2"
cyan = "#18b2b2"
green = "#18b218"
magenta = "#b218b2"
red = "#b21818"
white = "#b2b2b2"
yellow = "#b26818"

[colors.primary]
background = "#000000"
foreground = "#b2b2b2"

[colors.selection]
background = "#333333"
text = "#ffffff"
