- name: Start and enable services
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - NetworkManager
    - sshd
- name: Start and enable extra services
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"
