- name: Save foreign packages
  ansible.builtin.shell: "pacman -Qqm | grep -q {{pkg}}"
  ignore_errors: true
  register: is_installed

- name: "Download {{pkg}} from AUR"
  ansible.builtin.get_url:
    url: "https://aur.archlinux.org/cgit/aur.git/snapshot/{{pkg}}.tar.gz"
    dest: /tmp/
  register: tarball
  when: is_installed.rc == 1

- name: Extract the package
  ansible.builtin.unarchive:
    src: "{{ tarball.dest }}"
    dest: /tmp/
  when: is_installed.rc == 1

- name: Build the package
  ansible.builtin.command: makepkg --noconfirm --noprogressbar -mfs
  args:
    chdir: "/tmp/{{pkg}}"
  when: is_installed.rc == 1

- name: Install the package
  become: yes
  ansible.builtin.shell: "pacman --noconfirm --needed -U {{pkg}}*.pkg.tar.zst"
  args:
    chdir: "/tmp/{{pkg}}"
  when: is_installed.rc == 1

- name: Clean up
  ansible.builtin.file:
    path: "{{item}}"
    state: absent
  loop:
    - "/tmp/{{pkg}}"
    - "{{tarball.dest}}"
  when: is_installed.rc == 1
