- name: Create autologin conf folder
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    owner: root
    group: root
    state: directory
    mode: "0644"
- name: Autologin conf
  become: yes
  ansible.builtin.template:
    src: templates/autologin.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    owner: root
    group: root
    mode: "0644"
