- name: Install packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg:
      - blueman
      - bluez
      - bluez-utils
      - pulseaudio-bluetooth

- name: Start and enable service
  become: yes
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: yes
