- name: Check if devbox exists
  ansible.builtin.stat:
    path: /usr/local/bin/devbox
  register: devbox_bin
- name: Download devbox
  ansible.builtin.get_url:
    url: https://get.jetpack.io/devbox
    dest: /tmp/devbox_installer
    mode: '0770'
  register: devbox_installer
  when: not devbox_bin.stat.exists
- name: Install devbox
  ansible.builtin.command: /tmp/devbox_installer --force
  when: not devbox_bin.stat.exists
- name: Remove installer
  ansible.builtin.file:
    path: "{{ devbox_installer.dest }}"
    state: absent
  when: not devbox_bin.stat.exists
