- name: COPY LOCALE CONF
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/locale.conf"
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"
- name: COPY LOCALE GEN
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/locale.gen"
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: "0644"
  notify:
    - Generate locales
- name: COPY TIMEZONE
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/timezone"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
