- name: SET HOSTNAME
  ansible.builtin.hostname:
    name: "{{ host }}"

- name: SET USER
  become: yes
  ansible.builtin.user:
    name: "{{ user.username }}"
    shell: /bin/bash
    groups:
      "{{ ['users', 'wheel', 'disk', 'power', 'adm', 'network'] + user.groups }}"

- name: COPY LOCALE CONF
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/locale.conf"
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"

- name: COPY TIMEZONE
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/timezone"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"

- name: GENERATE LOCALES
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - en_US.UTF-8
    - it_IT.UTF-8
    - de_DE.UTF-8

- name: COPY CONSOLE FONTS
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/usr/share/kbd/consolefonts/{{ item }}"
    dest: /usr/share/kbd/consolefonts/
    owner: root
    group: root
    mode: "0644"
  loop:
    - spleen-5x8.psfu
    - spleen-6x12.psfu
    - spleen-8x16.psfu
    - spleen-12x24.psfu
    - spleen-16x32.psfu
    - spleen-32x64.psfu

- name: COPY VCONSOLE CONF
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/vconsole.conf"
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: "0644"

- name: CHECK NIX CONF
  local_action: "stat path=templates/{{ host }}/etc/nix/nix.conf"
  register: nixconf

- name: COPY NIX CONF
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/nix/nix.conf"
    dest: /etc/nix/nix.conf
    owner: root
    group: root
    mode: "0644"
  when: nixconf.stat.exists

- name: CHECK UDEV
  local_action: "stat path=templates/{{ host }}/etc/udev/rules.d/95-hdmi-plug.rules"
  register: udevrule

- name: COPY NIX CONF
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/udev/rules.d/95-hdmi-plug.rules"
    dest: /etc/udev/rules.d/95-hdmi-plug.rules
    owner: root
    group: root
    mode: "0644"
  when: udevrule.stat.exists

