- name: Force remove packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg:
      - asp
      - lftp
    state: absent
    update_cache: true

- name: Install packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg:
      - alacritty
      - ansible
      - base
      - base-devel
      - bash-completion
      - bat
      - cpupower
      - curl
      - eza
      - fd
      - ffmpegthumbnailer
      - figlet
      - fontconfig
      - fzf
      - gdu
      - git
      - gphoto2
      - gvfs-gphoto2
      - gvfs
      - inotify-tools
      - libnotify
      - mupdf
      - networkmanager
      - noto-fonts
      - noto-fonts-emoji
      - openssh
      - pavucontrol
      - pulseaudio
      - ripgrep
      - starship
      - stow
      - sudo
      - unzip
      - vim
      - wget
      - xorg
      - xorg-xinit

- name: Install extra packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg: "{{pkgs}}"

- name: Create base groups
  become: yes
  become_method: ansible.builtin.su
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - users
    - "{{ username }}"

- name: Create user
  become: yes
  become_method: ansible.builtin.su
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/bash
    groups:
      - users
      - disk
      - adm
      - audio
      - video
      - disk
      - sys
      - tty
      - daemon
      - input

- name: Add user to sudoers
  become: yes
  become_method: ansible.builtin.su
  community.general.sudoers:
    name: sudo
    state: present
    user: "{{ username }}"
    commands: ALL

- name: Set hostname
  become: yes
  ansible.builtin.hostname:
    name: "{{ host_name }}"

- name: Copy motd
  become: yes
  ansible.builtin.template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"

- name: Set timezone
  become: yes
  community.general.timezone:
    name: Europe/Vienna

- name: Copy locale conf
  become: yes
  ansible.builtin.copy:
    src: templates/locale.conf
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"

- name: Copy timezone
  become: yes
  ansible.builtin.copy:
    src: templates/timezone
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"

- name: Generate locales
  become: yes
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - en_US.UTF-8
    - it_IT.UTF-8
    - de_DE.UTF-8

- name: Start and enable services
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - NetworkManager
    - sshd
    - cpupower

- name: Copy cpupower conf
  become: yes
  ansible.builtin.copy:
    src: templates/cpupower
    dest: /etc/default/cpupower
    owner: root
    group: root
    mode: "0644"

- name: Copy console fonts
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ item }}"
    dest: /usr/share/kbd/consolefonts/
    owner: root
    group: root
    mode: "0644"
  loop:
    - spleen-5x8.psfu
    - spleen-6x12.psfu
    - spleen-8x16.psfu
    - spleen-12x24.psfu
    - spleen-16x32.psfu
    - spleen-32x64.psfu

- name: Copy console configuration
  become: yes
  ansible.builtin.copy:
    src: templates/vconsole.conf
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: "0644"

- name: Update font cache
  ansible.builtin.command: fc-cache -fv
