- name: CONFIGURE XFCE
  community.general.xfconf:
    channel: thunar
    property: "{{ item.p }}"
    value_type: "{{ item.t }}"
    value: "{{ item.v }}"
  loop:
    - {t: string, p: /default-view, v: ThunarIconView}
    - {t: bool, p: /misc-folders-first, v: false}
    - {t: bool, p: /misc-single-click, v: false}
    - {t: bool, p: /misc-text-beside-icons, v: false}
    - {t: string, p: /shortcuts-icon-size, v: THUNAR_ICON_SIZE_24}
    - {t: bool, p: /shortcuts-icon-emblems, v: false}
    - {t: bool, p: /misc-volume-management, v: false}
    - {t: bool, p: /last-statusbar-visible, v: false}
    - {t: bool, p: /last-menubar-visible, v: false}
