- community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/commands/custom/{{ item.prop }}"
    value_type: string
    value: "{{ item.val }}"
  loop:
    - { prop: <Alt>F2,            val: xfce4-appfinder }
    - { prop: <Alt><Shift>Return, val: alacritty }

- community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "/xfwm4/custom/{{ item.prop }}"
    value_type: string
    value: "{{ item.val }}"
  loop:
    - { prop: <Alt>Tab, val: cycle_windows_key }
    - { prop: <Alt>1, val: workspace_1_key }
    - { prop: <Alt>2, val: workspace_2_key }
    - { prop: <Alt>3, val: workspace_3_key }
    - { prop: <Alt>4, val: workspace_4_key }
    - { prop: <Alt>5, val: workspace_5_key }
    - { prop: <Alt>6, val: workspace_6_key }
    - { prop: <Alt>7, val: workspace_7_key }
    - { prop: <Alt>8, val: workspace_8_key }
    - { prop: <Alt>9, val: workspace_9_key }
    - { prop: <Alt><Shift>1, val: move_window_workspace_1_key }
    - { prop: <Alt><Shift>2, val: move_window_workspace_2_key }
    - { prop: <Alt><Shift>3, val: move_window_workspace_3_key }
    - { prop: <Alt><Shift>4, val: move_window_workspace_4_key }
    - { prop: <Alt><Shift>5, val: move_window_workspace_5_key }
    - { prop: <Alt><Shift>6, val: move_window_workspace_6_key }
    - { prop: <Alt><Shift>7, val: move_window_workspace_7_key }
    - { prop: <Alt><Shift>8, val: move_window_workspace_8_key }
    - { prop: <Alt><Shift>9, val: move_window_workspace_9_key }
    - { prop: <Alt><Shift>c, val: close_window_key }

- community.general.xfconf:
    channel: xfwm4
    property: "/general/{{ item.prop }}"
    value_type: "{{ item.type }}"
    value: "{{ item.val }}"
  loop:
    - { type: string, val: [1, 2, 3, 4, 5, 6, 7, 8, 9], prop: workspace_names }
    - { type: string, val: bring,   prop: activate_action }
    - { type: string, val: O|SHMC,  prop: button_layout }
    - { type: string, val: Alt,     prop: easy_click }
    - { type: int,    val: 0,       prop: button_offset }
    - { type: int,    val: 0,       prop: button_spacing }
    - { type: int,    val: 0,       prop: focus_delay }
    - { type: int,    val: 0,       prop: raise_delay }
    - { type: int,    val: 9,       prop: workspace_count }
    - { type: int,    val: 10,      prop: wrap_resistance }
    - { type: bool,   val: true,    prop: borderless_maximize }
    - { type: bool,   val: true,    prop: box_move }
    - { type: bool,   val: true,    prop: box_resize }
    - { type: bool,   val: false,   prop: click_to_focus }
    - { type: bool,   val: false,   prop: click_apps_only }
    - { type: bool,   val: true,    prop: cycle_draw_frame }
    - { type: bool,   val: true,    prop: cycle_hidden }
    - { type: bool,   val: false,   prop: cycle_minimized }
    - { type: bool,   val: true,    prop: cycle_minimum }
    - { type: bool,   val: true,    prop: cycle_preview }
    - { type: bool,   val: false,   prop: cycle_raise }
    - { type: bool,   val: true,    prop: focus_hint }
    - { type: bool,   val: true,    prop: focus_new }
    - { type: bool,   val: false,   prop: use_compositing }
    - { type: bool,   val: false,   prop: wrap_cycle }
    - { type: bool,   val: false,   prop: wrap_layout }
    - { type: bool,   val: false,   prop: wrap_windows }
    - { type: bool,   val: false,   prop: wrap_workspaces }
    - { type: bool,   val: true,    prop: zoom_desktop }
    - { type: bool,   val: true,    prop: zoom_pointer }

- community.general.xfconf:
    channel: xsettings
    property: "{{ item.prop }}"
    value_type: "{{ item.type }}"
    value: "{{ item.val }}"
  loop:
    - { type: string, val: "menu:minimize,maximize,close", prop: /Gtk/DecorationLayout }
    - { type: string, val: Noto Sans 14,  prop: /Gtk/FontName }
    - { type: string, val: Adwaita,       prop: /Gtk/CursorThemeName }
    - { type: string, val: Spleen 22,     prop: /Gtk/MonospaceFontName }
    - { type: string, val: icons,         prop: /Gtk/ToolbarStyle }
    - { type: string, val: hintfull,      prop: /Xft/HintStyle }
    - { type: string, val: rgb,           prop: /Xft/RGBA }
    - { type: int,    val: 48,            prop: /Gtk/CursorThemeSize }
    - { type: int,    val: 3,             prop: /Gtk/ToolbarIconSize }
    - { type: int,    val: 96,            prop: /Xft/DPI }
    - { type: int,    val: 1,             prop: /Xft/Antialias }
    - { type: int,    val: 1,             prop: /Xft/Hinting }
    - { type: bool,   val: true,          prop: /Gtk/ButtonImages }
    - { type: bool,   val: true,          prop: /Gtk/MenuImages }

- community.general.xfconf:
    channel: xfce4-notifyd
    property: "{{ item.prop }}"
    value_type: "{{ item.type }}"
    value: "{{ item.val }}"
  loop:
    - { type: string, val: [xfce4-power-manager], prop: /applications/known_applications }
    - { type: bool,   val: true,          prop: /log-max-size-enabled }
