add_newline = false

command_timeout = 800

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"


[nodejs]
symbol = "🚀 "

[git_status]
disabled = true

[package]
disabled = true
