add_newline = false

command_timeout = 800

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[git_status]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[purescript]
format = '[$symbol($version )]($style)'

[erlang]
format = '[$symbol($version )]($style)'
