#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width          2
bspc config window_gap            0
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config focus_follows_pointer true
bspc config right_padding         48
bspc config normal_border_color   "#222222"
bspc config focused_border_color  "#FF0000"

bspc rule -a Xfce4-panel layer=above manage=off border=off focus=off locked=on
bspc rule -a Xfce4-appfinder state=floating center=true follow=on rectangle=800x600+10+10

