---
- hosts: localhost
  gather_facts: no
  connection: local
  become: true
  become_method: ansible.builtin.su
  tasks:
    - name: Load vars
      ansible.builtin.include_vars:
        file: ../vars/personal.yml
    - name: Force remove packages
      community.general.pacman:
        pkg:
          - asp
          - lftp
        state: absent
        update_cache: true
    - name: Remove skel folder
      ansible.builtin.file:
        path: /etc/skel
        state: absent
    - name: Install packages
      community.general.pacman:
        pkg:
          - alacritty
          - ansible
          - base
          - base-devel
          - bash-completion
          - bat
          - cpupower
          - curl
          - eza
          - fd
          - ffmpegthumbnailer
          - figlet
          - fontconfig
          - fzf
          - gdu
          - git
          - git-lfs
          - gphoto2
          - gvfs-gphoto2
          - gvfs
          - incus
          - inotify-tools
          - libnotify
          - mupdf
          - networkmanager
          - noto-fonts
          - noto-fonts-emoji
          - openssh
          - pavucontrol
          - pulseaudio
          - ripgrep
          - starship
          - stow
          - sudo
          - unzip
          - vim
          - wget
          - xorg
          - xorg-xinit
    - name: Install extra packages
      community.general.pacman:
        pkg: "{{pkgs}}"
        force: true
    - name: Create base groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - users
        - "{{ username }}"
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        password: "$y$j9T$tjHMkn8tztrRUCBC5r1ME1$6Hmq71KYZJonIWT/ODqlxNURPvXVU84gdTUEm8mRtVD"
        groups:
          - adm
          - audio
          - daemon
          - disk
          - disk
          - incus
          - incus-admin
          - input
          - sys
          - tty
          - users
          - video
    - name: Add user to sudoers
      community.general.sudoers:
        name: sudo
        state: present
        user: "{{ username }}"
        commands: ALL
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    - name: Copy motd
      ansible.builtin.template:
        src: ../templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
    - name: Set timezone
      community.general.timezone:
        name: Europe/Vienna
    - name: Copy locale conf
      ansible.builtin.copy:
        src: ../templates/locale.conf
        dest: /etc/locale.conf
        owner: root
        group: root
        mode: 0644
    - name: Copy timezone
      ansible.builtin.copy:
        src: ../templates/timezone
        dest: /etc/timezone
        owner: root
        group: root
        mode: 0644
    - name: Generate locales
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop:
        - en_US.UTF-8
        - it_IT.UTF-8
        - de_DE.UTF-8
    - name: Start and enable services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - NetworkManager
        - sshd
        - cpupower
    - name: Copy cpupower conf
      ansible.builtin.copy:
        src: ../templates/cpupower
        dest: /etc/default/cpupower
        owner: root
        group: root
        mode: 0644
    - name: Copy console fonts
      ansible.builtin.copy:
        src: "../templates/{{ item }}"
        dest: /usr/share/kbd/consolefonts/
        owner: root
        group: root
        mode: 0644
      loop:
        - spleen-5x8.psfu
        - spleen-6x12.psfu
        - spleen-8x16.psfu
        - spleen-12x24.psfu
        - spleen-16x32.psfu
        - spleen-32x64.psfu
    - name: Copy console configuration
      ansible.builtin.copy:
        src: ../templates/vconsole.conf
        dest: /etc/vconsole.conf
        owner: root
        group: root
        mode: 0644
    - name: Update font cache
      ansible.builtin.command: fc-cache -f
