- name: COPY PACMAN CONF
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/pacman.conf"
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: "0644"

- name: SYNC PACMAN
  become: yes
  pacman:
    update_cache: yes

- name: INSTALL COMMON PACKAGES
  become: yes
  pacman:
    name:
      - base
      - base-devel
      - xorg
      - xorg-xinit
      - xorg-fonts-encodings
      - starship
      - fd
      - eza
      - bat
      - ripgrep
      - gdu
      - fzf
      - autorandr
      - awesome
      - xfce4-appfinder
      - xfce4-power-manager
      - elementary-icon-theme
      - keepassxc
      - thunar
      - tumbler
      - gvfs
      - gthumb
      - thunar-volman
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - ffmpegthumbnailer
      - poppler-glib
      - libgsf
      - libgepub
      - libopenraw
      - git
      - vim
      - terminus-font
      - noto-fonts
      - noto-fonts-emoji
      - bash-completion
      - inotify-tools
      - libiconv
      - upower
      - ansible
      - alacritty
      - firefox
      - fontconfig
      - openssh
      - stow
      - gphoto2
      - gvfs-gphoto2
    state: present
