# SYSTEM PACKAGES {{{
- name: Force remove packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg:
    - lftp
    state: absent
- name: Install packages
  become: yes
  become_method: ansible.builtin.su
  community.general.pacman:
    pkg:
    - alacritty
    - ansible
    - base
    - base-devel
    - bash-completion
    - bat
    - curl
    - elementary-icon-theme
    - eza
    - feh
    - fd
    - firefox
    - fontconfig
    - fzf
    - gdu
    - git
    - inotify-tools
    - keepass
    - libnotify
    - noto-fonts
    - noto-fonts-emoji
    - openssh
    - pavucontrol
    - pulseaudio
    - qutebrowser
    - ripgrep
    - starship
    - stow
    - sudo
    - vim
    - wget
    - xfce4
    - xfce4-goodies
    - xorg
    - xorg-xinit
    update_cache: true
# }}}

# USER AND GROUPS {{{
- name: Create base groups
  become: yes
  become_method: ansible.builtin.su
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - users
    - carloratm
- name: Create user
  become: yes
  become_method: ansible.builtin.su
  ansible.builtin.user:
    name: carloratm
    shell: /bin/bash
    groups:
      - users
      - disk
      - adm
      - audio
      - video
      - disk
      - sys
      - tty
      - daemon
      - input
- name: Add user to sudoers
  become: yes
  become_method: ansible.builtin.su
  community.general.sudoers:
    name: sudo
    state: present
    user: carloratm
    commands: ALL
# }}}

# SYSTEM CONFIG {{{
- name: Set hostname
  become: yes
  ansible.builtin.hostname:
    name: "{{ host }}"
- name: Set timezone
  become: yes
  community.general.timezone:
    name: Europe/Vienna
- name: Copy locale conf
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/locale.conf"
    dest: /etc/locale.conf
    owner: root
    group: root
    mode: "0644"
- name: Copy timezone
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/timezone"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
- name: Generate locales
  become: yes
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop:
    - en_US.UTF-8
    - it_IT.UTF-8
    - de_DE.UTF-8
# }}}

# GIT CONFIG {{{
- name: Config global git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - {name: user.name, value: "Ascani Carlo"}
    - {name: alias.co, value: checkout}
    - {name: alias.s, value: status}
    - {name: init.defaultBranch, value: main}
- name: Set git email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ email }}"
# }}}

# DOTFILES {{{
- name: Stow dotfiles
  ansible.builtin.shell: stow "{{ host }}" --target="{{lookup('env', 'HOME')}}"
  args:
    chdir: dotfiles
# }}}

# SERVICES {{{
- name: Start and enable serives
  become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - sshd
# }}}

# FONTS {{{
- name: Copy console fonts
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/usr/share/kbd/consolefonts/{{ item }}"
    dest: /usr/share/kbd/consolefonts/
    owner: root
    group: root
    mode: "0644"
  loop:
    - spleen-5x8.psfu
    - spleen-6x12.psfu
    - spleen-8x16.psfu
    - spleen-12x24.psfu
    - spleen-16x32.psfu
    - spleen-32x64.psfu
- name: Copy console configuration
  become: yes
  ansible.builtin.copy:
    src: "templates/{{ host }}/etc/vconsole.conf"
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: "0644"
- name: Update font cache
  ansible.builtin.command: fc-cache -fv
# }}}

# XFCE {{{
- name: Reset wallpapers
  ansible.builtin.command: xfconf-query --channel xfce4-desktop --property /backdrop --recursive --reset
- name: Reset shortcuts
  ansible.builtin.command: "xfconf-query --channel xfce4-keyboard-shortcuts --property {{item}} --recursive --reset"
  loop:
    - /commands/custom
    - /xfwm4/custom
- name: Set shortcuts overridable
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "{{item}}/override"
    value_type: bool
    value: true
  loop:
    - /commands/custom
    - /xfwm4/custom
- name: Set xfce commands keyboard shortcuts
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "{{item.p}}"
    value_type: string
    value: "{{item.v}}"
  loop:
    - {p: /commands/custom/<Alt>F2, v: xfce4-appfinder}
    - {p: /commands/custom/Print, v: xfce4-screenshooter}
    - {p: /commands/custom/<Alt><Shift>l, v: xflock4}
    - {p: /commands/custom/<Shift><Alt>Return, v: alacritty}
    - {p: /commands/custom/XF86Display, v: "xfce4-display-settings --minimal"}
- name: Set xfwm4 shortcuts
  community.general.xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "{{item.p}}"
    value_type: string
    value: "{{item.v}}"
  loop:
    - {p: /xfwm4/custom/<Alt><Shift>f, v: fullscreen_key}
    - {p: /xfwm4/custom/<Alt><Shift>c, v: close_window_key}
    - {p: /xfwm4/custom/<Alt>Tab, v: cycle_windows_key}
    - {p: /xfwm4/custom/<Alt><Shift>Tab, v: cycle_reverse_windows_key}
    - {p: /xfwm4/custom/Down, v: down_key}
    - {p: /xfwm4/custom/Up, v: up_key}
    - {p: /xfwm4/custom/Escape, v: cancel_key}
    - {p: /xfwm4/custom/Left, v: left_key}
    - {p: /xfwm4/custom/Right, v: right_key}
    - {p: /xfwm4/custom/<Alt>1, v: workspace_1_key}
    - {p: /xfwm4/custom/<Alt>2, v: workspace_2_key}
    - {p: /xfwm4/custom/<Alt>3, v: workspace_3_key}
    - {p: /xfwm4/custom/<Alt>4, v: workspace_4_key}
    - {p: /xfwm4/custom/<Alt>5, v: workspace_5_key}
    - {p: /xfwm4/custom/<Alt>6, v: workspace_6_key}
    - {p: /xfwm4/custom/<Alt>7, v: workspace_7_key}
    - {p: /xfwm4/custom/<Alt>8, v: workspace_8_key}
    - {p: /xfwm4/custom/<Alt>9, v: workspace_9_key}
    - {p: /xfwm4/custom/<Alt><Shift>1, v: move_window_workspace_1_key}
    - {p: /xfwm4/custom/<Alt><Shift>2, v: move_window_workspace_2_key}
    - {p: /xfwm4/custom/<Alt><Shift>3, v: move_window_workspace_3_key}
    - {p: /xfwm4/custom/<Alt><Shift>4, v: move_window_workspace_4_key}
    - {p: /xfwm4/custom/<Alt><Shift>5, v: move_window_workspace_5_key}
    - {p: /xfwm4/custom/<Alt><Shift>6, v: move_window_workspace_6_key}
    - {p: /xfwm4/custom/<Alt><Shift>7, v: move_window_workspace_7_key}
    - {p: /xfwm4/custom/<Alt><Shift>8, v: move_window_workspace_8_key}
    - {p: /xfwm4/custom/<Alt><Shift>9, v: move_window_workspace_9_key}
- name: Reset appfinder actions
  ansible.builtin.command: xfconf-query --channel xfce4-appfinder --property /actions --recursive --reset
- name: Set xfce appfinder
  community.general.xfconf:
    channel: xfce4-appfinder
    property: "{{item.p}}"
    value_type: "{{item.t}}"
    value: "{{item.v}}"
  loop:
    - {p: /always-center, t: bool, v: true}
    - {p: /enable-service, t: bool, v: true}
    - {p: /hide-category-pane, t: bool, v: true}
    - {p: /hide-window-decorations, t: bool, v: true}
    - {p: /hide-window-decorations, t: bool, v: true}
    - {p: /icon-view, t: bool, v: false}
    - {p: /item-icon-size, t: int, v: 2}
- name: Set xfce xsettings
  community.general.xfconf:
    channel: xsettings
    property: "{{item.p}}"
    value_type: "{{item.t}}"
    value: "{{item.v}}"
  loop:
    - {p: /Gdk/WindowScalingFactor, t: int, v: 1}
    - {p: /Gtk/ButtonImages, t: bool, v: true}
    - {p: /Gtk/CanChangeAccels, t: bool, v: false}
    - {p: /Gtk/CursorThemeName, t: string, v: Adwaita}
    - {p: /Gtk/CursorThemeSize, t: int, v: 48}
    - {p: /Gtk/DecorationLayout, t: string, v: "menu:minimize,maximize,close"}
    - {p: /Gtk/DialogsUseHeader, t: bool, v: false}
    - {p: /Gtk/FontName, t: string, v: "Noto Sans 12"}
    - {p: /Gtk/MonospaceFontName, t: string, v: "Spleen 15"}
    - {p: /Net/CursorBlink, t: bool, v: true}
    - {p: /Net/CursorBlinkTime, t: int, v: 1200}
    - {p: /Net/DndDragThreshold, t: int, v: 8}
    - {p: /Net/DoubleClickDistance, t: int, v: 5}
    - {p: /Net/DoubleClickTime, t: int, v: 400}
    - {p: /Net/EnableEventSounds, t: bool, v: false}
    - {p: /Net/EnableInputFeedbackSounds, t: bool, v: false}
    - {p: /Net/IconThemeName, t: string, v: elementary}
    - {p: /Net/SoundThemeName, t: string, v: default}
    - {p: /Net/ThemeName, t: string, v: Adwaita}
    - {p: /Xft/Antialias, t: int, v: 1}
    - {p: /Xft/Hinting, t: int, v: -1}
    - {p: /Xft/HintStyle, t: string, v: "hintfull"}
    - {p: /Xft/RGBA, t: string, v: "rgb"}
- name: Reset second panel
  ansible.builtin.command: xfconf-query --channel xfce4-panel --property /panels/panel-2 --recursive --reset
- name: Set xfce panels to only one
  community.general.xfconf:
    channel: xfce4-panel
    property: /panels
    value_type: int
    value: [1]
    force_array: true
- name: Set xfce panels
  community.general.xfconf:
    channel: xfce4-panel
    property: "{{item.p}}"
    value_type: "{{item.t}}"
    value: "{{item.v}}"
  loop:
    - {p: /panels/panel-1/icon-size, t: int, v: 16}
    - {p: /panels/panel-1/length, t: int, v: 100}
    - {p: /panels/panel-1/plugin-ids, t: int, v: [1,2,3,4,5,6,8,9,10,11,12,13,14]}
    - {p: /panels/panel-1/position, t: string, v: "p=6;x=0;y=0"}
    - {p: /panels/panel-1/position-locked, t: bool, v: true}
    - {p: /panels/panel-1/size, t: int, v: 24}
- name: Set xfce session
  community.general.xfconf:
    channel: xfce4-session
    property: "{{item.p}}"
    value_type: "{{item.t}}"
    value: "{{item.v}}"
  loop:
    - {p: /general/FailsafeSessionName, t: string, v: Failsafe}
    - {p: /general/LockCommand, t: string, v: xflock4}
    - {p: /general/SaveOnExit, t: bool, v: false}
- name: Set Failsafe session
  community.general.xfconf:
    channel: xfce4-session
    property: "/sessions/Failsafe/{{item.p}}"
    value_type: "{{item.t}}"
    value: "{{item.v}}"
    force_array: "{{item.a}}"
  loop:
    - {p: Client0_Command, t: string, v: ["xfwm4"], a: true}
    - {p: Client0_PerScreen, t: bool, v: false, a: false}
    - {p: Client0_Priority, t: int, v: 15, a: false}
    - {p: Client1_Command, t: string, v: ["xfsettingsd"], a: true}
    - {p: Client1_PerScreen, t: bool, v: false, a: false}
    - {p: Client1_Priority, t: int, v: 20, a: false}
    - {p: Client2_Command, t: string, v: ["xfce4-panel"], a: true}
    - {p: Client2_PerScreen, t: bool, v: false, a: false}
    - {p: Client2_Priority, t: int, v: 25, a: false}
    - {p: Client3_Command, t: string, v: ["Thunar", "--daemon"], a: true}
    - {p: Client3_PerScreen, t: bool, v: false, a: false}
    - {p: Client3_Priority, t: int, v: 30, a: false}
    - {p: Client4_Command, t: string, v: ["xfdesktop"], a: true}
    - {p: Client4_PerScreen, t: bool, v: false, a: false}
    - {p: Client4_Priority, t: int, v: 35, a: false}
    - {p: Count, t: int, v: 5, a: false}
    - {p: IsFailsafe, t: bool, v: true, a: false}
# }}}
