import:
  - ~/.config/alacritty/dark.yml

draw_bold_text_with_bright_colors: true

font:
  normal:
    family: Astacid
    style: Regular

  bold:
    family: Astacid
    style: Regular

  italic:
    family: Astacid
    style: Regular

  bold_italic:
    family: Astacid
    style: Regular

  size: 20

mouse:
  hide_when_typing: true

TERM: xterm-256color

window:
  dimensions:
    columns: 80
    lines: 20

key_bindings:
  - { key: F11, action: ToggleFullscreen }
