colors:
  name: "Dark Theme"
  author: "Carlo Ascani (https://tilde.club/~carloratm)"
  description: "My personal dark Theme"
  primary:
    foreground: "#b2b2b2"
    background: "#000000"
  cursor:
    text: "#000000"
    cursor: "#b2b2b2"
  selection:
    text: "#ffffff"
    background: "#333333"
  normal:
    black: "#202020"
    red: "#b21818"
    green: "#18b218"
    yellow: "#b26818"
    blue: "#2222ff"
    magenta: "#b218b2"
    cyan: "#18b2b2"
    white: "#b2b2b2"
  bright:
    black: "#686868"
    red: "#ff5454"
    green: "#54ff54"
    yellow: "#ffff54"
    blue: "#5454ff"
    magenta: "#ff54ff"
    cyan: "#54ffff"
    white: "#ffffff"
