colors:
  name: "Alacritty theme"
  author: "Ascani Carlo"
  description: "Light theme for prose or for coding"
  primary:
    foreground: "#343434"
    background: "#e4e4e4"
  cursor:
    text: "#ffffff"
    cursor: "#4a484d"
  selection:
    text: "#ffffff"
    background: "#4a484d"
  normal:
    black: "#333333"
    red: "#a50000"
    green: "#005d26"
    yellow: "#BB7500"
    blue: "#1458EC"
    magenta: "#88267a"
    cyan: "#005f87"
    white: "#999999"
  bright:
    black: "#000000"
    red: "#992030"
    green: "#4a5500"
    yellow: "#8a3600"
    blue: "#2d45b0"
    magenta: "#700dc9"
    cyan: "#005289"
    white: "#bbbbbb"
