#!/bin/sh

logfile="$HOME/.dkrc.log"
: > "$logfile"

# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
    pkill sxhkd
    sxhkd -c "$HOME/.config/dk/sxhkdrc" &
fi

{
    dkcmd set numws=9
    dkcmd set ws=_ apply \
        layout=tile \
        master=1 \
        stack=3 \
        gap=0 \
        msplit=0.55 \
        ssplit=0.5
    dkcmd set \
        focus_open=true \
        focus_urgent=true \
        focus_mouse=true
    dkcmd set \
        tile_tohead=0 \
        tile_hints=false
    dkcmd set win_minwh=50 win_minxy=10
    dkcmd set smart_gap=true smart_border=true
    dkcmd set mouse mod=alt move=button1 resize=button3
    dkcmd set obey_motif=true
    dkcmd set border \
        width=2 \
        colour \
            focus='#ff0000' \
            unfocus='#303030' \
            urgent='#ff0000'

    dkcmd rule class="^(pavucontrol|appfinder)$" float=true
    dkcmd rule class="^(alacritty|xterm|xterm-256colors)$" terminal=true
    dkcmd rule title="^Event Tester$" no_absorb=true
    dkcmd rule apply '*'

    xdotool set_desktop 0

} >> "$logfile" 2>&1

if grep -q 'error:' "$logfile"
then
    hash notify-send && notify-send -t 0 -u critical "dkrc has errors" \
        "$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"); print}' "$logfile")"
    exit 1
fi

exit 0
