tiling_enabled = true
tiling_layout = "vertical-left"
tiling_cycle = [
    "vertical-left",
    "horizontal-top",
    "maximized",
]
tiling_gui = 0
tiling_icon = [
    ["toggle", "Enabled"],
    ["decoration", "Decoration"],
    ["", ""],
    ["reset", "Reset"],
    ["", ""],
    ["exit", "Exit"],
]

window_ignore = [
    ["nm.*", ""],
    ["gcr.*", ""],
    ["polkit.*", ""],
    ["wrapper.*", ""],
    ["lightdm.*", ""],
    ["blueman.*", ""],
    ["pavucontrol.*", ""],
]

window_masters_max = 1
window_slaves_max = 4
window_gap_size = 0
window_focus_delay = 0
window_decoration = true
proportion_step = 0.08
proportion_min = 0.1
edge_margin = [0, 48, 0, 0]
edge_margin_primary = [0, 0, 0, 0]
edge_corner_size = 0
edge_center_size = 0

[colors]
gui_text = [255, 255, 255, 255]
gui_background = [30, 30, 40, 255]
gui_client_slave = [58, 58, 78, 255]
gui_client_master = [98, 98, 128, 255]
icon_background = [0, 0, 0, 0]
icon_foreground = [255, 255, 255, 255]

[keys]
toggle = "Mod1-t"
decoration = "Mod1-d"
cycle_next = "Mod1-Space"
#window_next = "Mod1-k"
#window_previous = "Mod1-j"
master_make = "Mod1-Return"
proportion_increase = "Mod1-l"
proportion_decrease = "Mod1-h"
mod_screens = "Mod4"
mod_workspaces = "Mod4"

[corners]
top_left = ""
top_center = ""
top_right = ""
center_right = ""
bottom_right = ""
bottom_center = ""
bottom_left = ""
center_left = ""

[systray]
click_left = ""
click_middle = "toggle"
click_right = ""
scroll_up = ""
scroll_down = ""
scroll_left = ""
scroll_right = ""
