name: Dotfiles CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install incus
        run: |
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus

      - name: Reset the firewall
        run: sudo nft flush ruleset

      - name: Init incus
        run: sudo incus admin init --auto

      - name: Start incus
        run: sudo systemctl start incus

      - name: Launch an arch container
        run: sudo incus launch images:b0b987c75be9 archbox

      - name: Install ansible on arch
        run: |
          sleep 10
          sudo incus exec archbox -- pacman -Syyu --noconfirm
          sudo incus exec archbox -- pacman -S ansible
          sudo incus exec archbox -- ansible --version

      - name: Copy files to arch
        run: sudo incus file push -r * archbox/root/

      - name: Run the sys playbook
        run: |
          sudo incus exec archbox -- usermod --password ONACIIAMHAPPY root
          sudo incus exec archbox -- sudo ansible-playbook --inventory inventory -e "ansible_sudo_pass=ONACIIAMHAPPY" -e hostname=scumm plays/sys.yml
