name: Dotfiles CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install incus
        run: |
          sudo mkdir -p /etc/apt/keyrings/

          sudo curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc

          sudo sh -c 'cat <<EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
          Components: main
          Architectures: $(dpkg --print-architecture)
          Signed-By: /etc/apt/keyrings/zabbly.asc

          EOF'

          sudo apt-get update

          sudo apt-get install incus

          sudo incus admin init --auto

          sudo systemctl start incus

          sudo incus admin waitready

          sudo incus launch images:archlinux/cloud archbox --vm -c security.secureboot=false

          sudo incus exec archbox -- pacman --version
