name: Dotfiles CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install incus
        run: |
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus

      - name: Init incus
        run: sudo incus admin init --auto

      - name: Start incus
        run: sudo systemctl start incus

      - name: Launch an arch container
        run: sudo incus launch images:b0b987c75be9 archbox

      - name: Install ansible on arch
        run: |
          sudo iptables -I DOCKER-USER -i incusbr0 -j ACCEPT
          sudo iptables -I DOCKER-USER -o incusbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          sleep 10
          sudo incus list
          sudo incus config show archbox
          sudo incus exec archbox -- ping -c 5 google.com
          sudo incus exec archbox -- ping -c 5 mirrors.kernel.org
          sudo incus exec archbox -- pacman -S ansible --noconfirm
