name: My Dotfiles CI

on:
  push:
    branches: [debian]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint playbooks
        uses: ansible/ansible-lint@main

  build:
    name: Ansible run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Step 1 - Install and start incus
        run: |
          sudo nft flush ruleset
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus
          sudo incus admin init --auto
          sudo systemctl start incus

      - name: Step 2 - Launch a debian container
        run: |
          sudo incus launch images:debian/12/cloud workstation
          until [[ -n $(sudo incus list workstation -c4 -fcsv) ]]
          do
            echo "Waiting for the vm interface to be up..."
            sleep 1
          done
          sudo incus exec workstation -- apt install --yes openssh-server ansible make

      - name: Step 3 - Set up ssh
        run: |
          cat > enable_ssh_root << EOF
          PermitRootLogin yes
          StrictModes no
          EOF
          sudo incus file push enable_ssh_root workstation/etc/ssh/sshd_config.d/enable_ssh_root
          sudo incus exec workstation -- systemctl restart sshd
          mkdir ~runner/.ssh
          ssh-keygen -q -t rsa -N '' -f ~runner/.ssh/id_rsa <<<y >/dev/null 2>&1
          sudo incus file push ~runner/.ssh/id_rsa.pub workstation/root/.ssh/authorized_keys

      - name: Step 4 - Run the playbook
        run: |
          sudo incus exec workstation -- make ANSIBLE_HOST_KEY_CHECKING=False workstation
