name: My Dotfiles CI

on:
  push:
    branches: [void]

jobs:
  build:
    name: Ansible lint and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reset the firewall
        run: sudo nft flush ruleset

      - name: Install and start incus
        run: |
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus
          sudo incus admin init --auto
          sudo systemctl start incus

      - name: Launch a Voidlinux container
        run: sudo incus launch images:voidlinux void

      - name: Install pre-requisites on void
        run: |
          sleep 10
          sudo incus exec void -- xbps-install --yes make ansible python3-ansible-lint

      - name: Copy this repository files to void
        run: sudo incus file push -r * void/root/

      - name: Lint allthethings
        run: sudo incus exec void -- ansible-lint

      - name: Run the playbook
        run: sudo incus exec void -- make CI=true workstation
