name: CI

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint playbooks
        uses: ansible/ansible-lint@main

  build:
    strategy:
      matrix:
        profile: [workstation, mediacenter]
    name: Ansible run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run play and tests
        run: |
          sudo nft flush ruleset
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus
          sudo incus admin init --auto
          sudo systemctl start incus

          PROFILE=${{ matrix.profile }}

          sudo incus launch images:debian/12/cloud $PROFILE
          sudo incus file push -rp * $PROFILE/root/
          sudo incus exec $PROFILE -- apt install --yes ansible make
          sudo incus exec $PROFILE -- make CI=true LOCAL=true $PROFILE
          sudo incus exec $PROFILE -- ./local/bin/runtests.sh
