name: CI

on:
  push:
    branches: [debian]

jobs:
  strategy:
    matrix:
      profile: [workstation]

  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint playbooks
        uses: ansible/ansible-lint@main

  build:
    name: Ansible run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Arrange
        run: |
          sudo nft flush ruleset
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus ansible make
          sudo incus admin init --auto
          sudo systemctl start incus

          PROFILE=${{ matrix.profile }}
          sudo incus launch images:debian/12/cloud $PROFILE
          until [[ -n $(sudo incus list $PROFILE -c4 -fcsv) ]]
          do
            echo "Waiting for the vm interface to be up..."
            sleep 1
          done
          CONTAINER_IP=$(sudo incus list $PROFILE -c4 -fcsv | cut -d ' ' -f1)
          sudo incus exec $PROFILE -- apt install --yes openssh-server ansible make

          cat > enable_ssh_root << EOF
          PermitRootLogin yes
          StrictModes no
          EOF
          sudo incus file push enable_ssh_root $PROFILE/etc/ssh/sshd_config.d/enable_ssh_root
          sudo incus exec $PROFILE -- systemctl restart sshd
          sudo ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa
          sudo incus file push /root/.ssh/id_rsa.pub $PROFILE/root/.ssh/authorized_keys
          sudo ssh -o "StrictHostKeyChecking=no" root@${CONTAINER_IP} "lsb_release -a"

      - name: Act
        run: |
          CONTAINER_IP=$(sudo incus list $PROFILE -c4 -fcsv | cut -d ' ' -f1)
          sudo make CI=true ANSIBLE_HOST_KEY_CHECKING=False TARGET=${CONTAINER_IP} $PROFILE
