name: Workstation

on:
  push:
    branches: [master]

jobs:
  build:
    name: Ansible lint and run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reset the firewall
        run: sudo nft flush ruleset

      - name: Install and start incus
        run: |
          sudo mkdir -p /etc/apt/keyrings
          wget -qO - https://pkgs.zabbly.com/key.asc | sudo tee /etc/apt/keyrings/zabbly.asc
          sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/zabbly-incus-stable.sources
          Enabled: yes
          Types: deb
          URIs: https://pkgs.zabbly.com/incus/stable
          Suites: jammy
          Components: main
          Architectures: amd64
          Signed-By: /etc/apt/keyrings/zabbly.asc
          EOF'
          sudo apt update
          sudo apt install incus
          sudo incus admin init --auto
          sudo systemctl start incus

      - name: Launch a Voidlinux workstation system
        run: sudo incus launch images:voidlinux workstation

      - name: Install pre-requisites on workstation
        run: |
          sleep 10
          sudo incus exec workstation -- xbps-install --yes make ansible python3-ansible-lint

      - name: Copy this repository files to workstation
        run: sudo incus file push -r * workstation/root/

      - name: Lint allthethings on workstation
        run: sudo incus exec workstation -- ansible-lint

      - name: Run the playbook on workstation
        run: sudo incus exec workstation -- make CI=true workstation

      - name: Asserts on workstation
        run: |
          sudo incus exec workstation -- id carloratm
          sudo incus exec workstation -- ls -d /home/carloratm
          sudo incus exec workstation -- ls -d /var/service/cronie
          sudo incus exec workstation -- ls /home/carloratm/.local/bin/xmonad
          sudo incus exec workstation -- ls /home/carloratm/.local/bin/colors.sh
          sudo incus exec workstation -- ls /usr/local/bin/devbox
          sudo incus exec workstation -- ls /etc/vimrc.local
          sudo incus exec workstation -- grep "FONT=\"spleen-" /etc/rc.conf
          sudo incus exec workstation -- which keepassxc
